### ISSUE TITLE
Problemas no servidor?

### ISSUE THREAD

**Issue by marcgtsr** [Contadoria/Tutoriais#4]
Estou tentando importar os dados do CNIS e sempre da erro, é normal?

Ainda nao consegui usar as planilhas por esses erros, queria saber se eu estou fazendo algo errado ou se elas realmente nao funcionam mais. Obrigado

**Comment by efujit** [comment]
Acredito que esta issue foi resolvida conforme [issue 17 de CalculoTC](https://github.com/Contadoria/CalculoTC/issues/17).
Caso persista a dúvida, peço para reabrir.
